services:
  prompter.client:
    image: prompter.client
    build:
      context: ./Prompter.Client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - prompter.web

  prompter.web:
    image: prompter.web
    build:
      context: .
      dockerfile: Prompter.Web/Dockerfile
    ports:
      - "5251:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=prompter;Username=postgres;Password=postgres
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres

  prompter.worker:
    image: prompter.worker
    build:
      context: .
      dockerfile: Prompter.Worker/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=prompter;Username=postgres;Password=postgres
      - Ollama__BaseUrl=http://ollama:11434
      - Ollama__Model=phi3
    depends_on:
      - postgres
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: ["/bin/sh", "-c", "ollama serve & sleep 5 && ollama pull phi3 && wait"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prompter
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  ollama_data:
  postgres_data:

